[client]
showErrorDetails = true

[server]
maxUploadSize = 1024
port = 8501
headless = true
fileWatcherType = "none"
runOnSave = false
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "error"

[browser]
gatherUsageStats = false
